// Accessibility Core Exports
export * from './audio/AudioTypes';
export * from './audio/EarconManager';
export * from './audio/AcousticManager';
export * from './haptic/HapticManager';
export * from './events/AccessibilityEvents';
export * from './events/AccessibilityEventBus';
export * from './i18n/a11yDictionary';
export * from './useAccessibility';
export * from './AccessibilityProvider';
export * from './sonification/SonificationEngine';
